### ISSUE TITLE
Failed to update metrics (player)

### ISSUE THREAD

**Issue by mr190e** [WoozyMasta/dayz-exporter#2]
since the last update (I pulled it more or less accidently via docker because I changed some settings), I get these errors:

```
2025-02-01T22:27:05Z ERR Failed to send 'players' command error="connection to server is down, need reconnect"

2025-02-01T22:27:05Z ERR Error updating metrics error="connection to server is down, need reconnect" context=player

2025-02-01T22:27:05Z FTL Failed to update metrics (player)
```

It almost looks to me like either RCON is down, but this would be really weird as it just worked until before the update. I think I came from version 0.1.1

Has there been a change in the config maybe?

**Comment by WoozyMasta** [comment]
Probably just the logs became more detailed

If you had problems with the configuration, the exporter would not start at all, since the first thing it does is check the connection and try to initialize the metrics. You would simply get the error "Failed to establish connections to RCON" when starting.

According to the description, it looks more like your server is being restarted according to a schedule. And while the DayZ server is off, an attempt is made to collect metrics.

And if this is so, then this is normal behavior, because the server is currently off, you can just forget about it, and let the exporter also restart with the server shutdown. Or if you want a correct termination, then stop and start the exporter yourself along with the server restart.

**Comment by mr190e** [comment]
When I role back to version 0.3.0 everything is fine. Its just that since 0.3.1 nothing seems to work anymore. I didnt touch anything in configs. I just so happen to stop the docker container and I renamed them, which lead to re-pulling the latest image (I had this checkbox checked).

**Comment by WoozyMasta** [comment]
When does the problem occur? Immediately upon launching the application, or after some time? If after some time, then after what time and how often?

---

I can't reproduce this problem, and between 0.3.0 and 0.3.1 there were no changes in this part

```bash
# get 0.3.1 image and config example

docker pull ghcr.io/woozymasta/dayz-exporter:0.3.1
docker run --rm -ti ghcr.io/woozymasta/dayz-exporter:latest \
  --get-yaml > dayz-exporter-tmp.yaml

# change ip, port and password in dayz-exporter-tmp.yaml and run it

docker run  --rm -ti -p 8098:8098 \
  -v "$PWD/dayz-exporter-tmp.yaml:/config.yaml" \
  ghcr.io/woozymasta/dayz-exporter:0.3.1
```

I just launched it, everything works

```txt
2025-02-11T10:03:44Z INF Connected to "WM vanilla [Cherno]" (chernarusplus) server on 192.168.1.12:27021
2025-02-11T10:03:44Z INF Starting metrics server at 0.0.0.0:8098
2025-02-11T10:04:09Z INF HTTP request completed duration=0.049274 method=GET remote=10.0.2.100:41302 size=2546 status=200 url=/
2025-02-11T10:04:09Z INF HTTP request completed duration=0.035708 method=GET remote=10.0.2.100:41302 size=2546 status=200 url=/favicon.ico
2025-02-11T10:04:11Z TRC Server A2S metrics updated
2025-02-11T10:04:11Z TRC Player metrics updated
2025-02-11T10:04:11Z DBG Ban metrics disabled, skipping update
2025-02-11T10:04:11Z DBG Metrics updated
2025-02-11T10:04:11Z INF HTTP request completed duration=83.028991 method=GET remote=10.0.2.100:41302 size=2261 status=200 url=/metrics
2025-02-11T10:04:16Z TRC Server A2S metrics updated
2025-02-11T10:04:16Z TRC Player metrics updated
2025-02-11T10:04:16Z DBG Ban metrics disabled, skipping update
2025-02-11T10:04:16Z DBG Metrics updated
2025-02-11T10:04:16Z INF HTTP request completed duration=61.519443 method=GET remote=10.0.2.100:41302 size=2279 status=200 url=/metrics
```

I changed the password to a deliberately incorrect one and it doesn't work

```txt
2025-02-11T10:04:37Z FTL Failed to establish connections to RCON port 192.168.1.12:23015
```

changed the port to a known wrong one and it doesn't work

```txt
2025-02-11T10:05:12Z FTL Failed to establish connections to RCON port 192.168.1.12:2301
```

Everything works correctly, metrics are collected, if the config is incorrect the application simply does not start

---

Or maybe you use both the config and environment variables at the same time?

```bash
DAYZ_EXPORTER_RCON_PASSWORD=right
```

and in the config

```yaml
rcon:
password: wrong
```

the config in this case has a higher priority than the environment variables, this is written in the help

**Comment by slapcat** [comment]
I was getting the same error on a fresh setup. It seemed to be something in the default config I copied because once I trimmed out any settings I didn't need, it started working. If this doesn't work, maybe it would be work sharing your config @mr190e ?

**Comment by WoozyMasta** [comment]
@slapcat, do you remember what exactly caused the configuration difficulties? I can't see the problem.

**Comment by slapcat** [comment]
My original attempt when I ran into the issue was using the [example YAML](https://github.com/WoozyMasta/dayz-exporter/blob/master/cli/example.config.yaml) and only updating the server IPs and RCON password, leaving all other lines as is. 

I just tried again and could reproduce it, but the error only occurs when you query /metrics endpoint. If you don't query it, everything seems to run fine. A simple curl to [dayz-exporter]:8098/metrics should trigger the error if you use this config YAML:
```
---
## Configuration for the exporter listening parameters
listen:
  ip: 0.0.0.0  # IP address to listen (DAYZ_EXPORTER_LISTEN_IP)
  port: 8098  # Port number to listen on for incoming HTTP requests (DAYZ_EXPORTER_LISTEN_PORT)
  endpoint: /metrics  # HTTP endpoint where Prometheus metrics will be exposed (DAYZ_EXPORTER_LISTEN_ENDPOINT)
  username: metrics  # Username used for all exporter endpoints.
  # password: SomeStrongString  # Password used for all exporter endpoints (Basic Auth disabled if not set).
  health_auth: false  # Protect /health, /health/readiness and /health/liveness with Basic Auth

## Configuration for querying the DayZ server (A2S Query)
query:
  ip: &server 10.10.1.90  # IP address of the server (DAYZ_EXPORTER_QUERY_IP)
  port: 27016  # Port number for DayZ query (DAYZ_EXPORTER_QUERY_PORT)

## Configuration for querying the DayZ Remote Console (Battleye RCON)
rcon:
  ip: *server  # IP address of the RCON. It uses the same IP as the query server (DAYZ_EXPORTER_RCON_IP)
  port: 2305  # Port number for RCON. (DAYZ_EXPORTER_RCON_PORT)
  password: SomeStrongString # Password for RCON authentication. (DAYZ_EXPORTER_RCON_PASSWORD)
  expose_bans: false  # Whether to expose ban information via metrics. (DAYZ_EXPORTER_RCON_EXPOSE_BANS)
  buffer_size: 1040  # The size of the buffer used for RCON communication (DAYZ_EXPORTER_RCON_BUFFER_SIZE)
  keepalive_timeout: 30  # The timeout in seconds for keeping the RCON connection alive (DAYZ_EXPORTER_RCON_KEEPALIVE_TIMEOUT)
  deadline_timeout: 5  # The timeout in seconds for RCON command execution (DAYZ_EXPORTER_RCON_DEADLINE_TIMEOUT)

## Custom labels to be added to the metrics, can be useful for distinguishing between servers or clusters
# labels:  # Example : (DAYZ_EXPORTER_LABELS="dc:EU-2,rack:U4")
#   dc: HV-1  # Data center identifier. Example label
#   rack: U4  # Rack identifier within the data center. Example label

## Path to the GeoIP database for IP geolocation (used for enriching players and bans data with location info)
# geo_db: ./GeoLite2-Country.mmdb  # Path to the MaxMind GeoLite2 country database file. (DAYZ_EXPORTER_GEOIP_DB)

## Logging configuration
logging:
  level: info  # Logging level. Options: 'debug', 'info', 'warn', 'error' (DAYZ_EXPORTER_LOG_LEVEL)
  format: text  # Logging format. Options: 'text' (human-readable) or 'json' (structured) (DAYZ_EXPORTER_LOG_FORMAT)
  output: stdout  # Output destination for logs. Options: 'stdout' (default) or 'stderr' or a file path (DAYZ_EXPORTER_LOG_OUTPUT)
```
